[package]
name = "waveview"
default-run = "waveview_bin"
version = "0.1.0"
authors = ["Christopher Chalmers <c.chalmers@me.com>"]
edition = "2021"
rust-version = "1.92"

[workspace]
members = [
    "eprompt",
    "timeline",
    "waveserve",
    "waveview-model",
    "waveview-ui",
    "waveview-ui-reload",
]
default-members = ["."]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "waveview_bin"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.35.0"
ehttp = "0.6.0"
ewebsock = { version = "0.8.0", features = ["tls"] }
color-eyre = "0.6.5"
itertools = "0.14"
log = "0.4"
rfd = "0.15"
futures = { version = "0.3", features = ["executor"] }
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.5", features = ["derive"] }

serde = { version = "1", features = ["derive"], optional = true }

egui_dnd = "0.16.0"
waveview-model = { path = "waveview-model" }
waveview-ui = { path = "waveview-ui" }
hot-lib-reloader = { version = "0.8.2", optional = true }
waveview-ui-reload = { path = "waveview-ui-reload", optional = true }

[features]
default = ["persistence"]
persistence = ["eframe/persistence", "serde"] # Enable if you want to persist app state on shutdown
reload = ["dep:hot-lib-reloader", "dep:waveview-ui-reload"]

# [profile.release]
# opt-level = 2 # fast and small wasm

# [patch.crates-io]

# If you want to use the bleeding edge version of `egui`:
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

# If you fork https://github.com/emilk/egui you can test with:
# eframe = { path = "../egui/eframe" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2"
wasm-bindgen = "=0.2.121"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "*"
features = [
  "BinaryType",
  "Blob",
  "ErrorEvent",
  "FileReader",
  "HtmlCanvasElement",
  "Location",
  "MessageEvent",
  "ProgressEvent",
  "WebSocket",
]
